# GitHub Sponsors funding file
# For commercial licensing inquiries, please contact: [your-email@example.com]

# You can add funding platforms here if you want to accept donations
# github: [shipdocs]
# patreon: username
# ko_fi: username

custom: ["mailto:your-email@example.com?subject=Commercial%20License%20Inquiry"]
